// default package
// Generated 2014-mar-06 12:12:54 by Hibernate Tools 4.0.0

/**
 * UsersId generated by hbm2java
 */
public class UsersId implements java.io.Serializable {

	private int userId;
	private String name;

	public UsersId() {
	}

	public UsersId(int userId, String name) {
		this.userId = userId;
		this.name = name;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersId))
			return false;
		UsersId castOther = (UsersId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
